### ISSUE TITLE
How to get images

### ISSUE THREAD

**Issue by zapcriativo** [charanpy/ReactNative-InstagramClone#1]
Hi @charanpy 

Congratulations on the work !!

How do I get the list of selected images to send to my reducer api?

**Comment by charanpy** [comment]
Hey sorry for late reply.Whenever component mounts, a default image (first image of default album) added to state.There is an option for choosing multiple images.Default option is selecting single image.When ever user clicks an image new array with selected image added to state. When user selects multiple image option , selected image will be pushed to state.
